### ISSUE TITLE
Add helper method for shielding transparent funds

### ISSUE THREAD

**Issue by str4d** [zcash/zcash-devtool#22]
Once #21 is implemented, we should add a method that will shield any transparent funds in the wallet. This should match how we implement it in the mobile SDKs: by default we should only shield one receiver at a time, and thus if we have multiple receivers containing transparent funds we will need the call to specify which one to shield.

Creating multiple transactions at once to shield funds present in multiple transparent receivers is out-of-scope for this issue.

**Comment by nuttycom** [comment]
`zcash-devtool wallet shield` exists.
