### ISSUE TITLE
Add support for interacting with accounts after the first

### ISSUE THREAD

**Issue by str4d** [zcash/zcash-devtool#34]
The commands currently just use whatever the first account is, because that's all we've needed so far. We recently added support for importing a UFVK, but in order to use it with the other commands it needs to be the first account in the wallet (i.e. init a wallet with no accounts, then import).

We should add some way to specify the account to use with a given command (where it is relevant). This might require adding a command to expose the internal account indices to use as account selectors, or otherwise defining some way to refer to a specific account from the CLI.

**Comment by nuttycom** [comment]
This is complete with the switch to account UUIDs.
